[network]
name = "Base Sepolia"
chain_id = 84532
confirmation_blocks = 1

[rpc]
primary_url = "https://base-sepolia.g.alchemy.com/v2/keg5qPpXALLYHHhXJBKuL"
fallback_url = "https://fluent-empty-meadow.base-sepolia.quiknode.pro/a9ebb15ae2a849c069efd78d24022e2e60c1be1f/"
public_url = "https://sepolia.base.org"
timeout_seconds = 30
max_retries = 3

[gas]
safety_margin_percent = 20
max_priority_fee_gwei = 2.0
max_base_fee_gwei = 100.0

[reserves]
minimum_balance_eth = 0.01
warning_threshold_eth = 0.05
critical_threshold_eth = 0.02

[quotes]
validity_duration_minutes = 10
max_amount_eth = 1.0
min_amount_eth = 0.001

[logging]
level = "debug"
enable_request_logging = true
